### ISSUE TITLE
Ship a v2.0.1 AMI

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/marketplace-ami#1]
The most recent AMI available in the AWS Marketplace is 1.16.2. Can you release an update for v2.0.1?

**Comment by AtnNn** [comment]
We're in the process of getting it on the marketplace. There is some discussion about it here: https://github.com/rethinkdb/rethinkdb/issues/4141

You can try the candidate AMI for 2.0.1: `ami-1addd172`.

To upgrade to 2.0.1 you can also ssh into your 1.16.3 instance and run `apt-get update && apt-get install rethinkdb`

**Comment by danielcompton** [comment]
Awesome, thanks! I'll follow this on the other ticket.
